# -*- coding: utf-8 -*-
"""
Generates assets/js/hero-portrait-data.js — the point data behind the
hero portrait's frame-to-ammonite morph (see assets/js/hero-portrait.js
for how it's used).

Two closed shapes, each sampled at the same N angles from the same
center so they can be linearly interpolated point-by-point:

  - HERO_MORPH_BLOB: a calm organic "living" outline (a few sine
    harmonics summed over the radius) — the frame's resting shape
    around the portrait photo.
  - HERO_MORPH_AMMONITE: the real outer silhouette of an ammonite
    shell — one full turn of a logarithmic spiral (the actual growth
    curve ammonite shells follow), closed into a loop. The radius
    jump where the turn closes (theta wraps from 2*pi back to 0) is
    softened over a short arc but deliberately kept as a visible
    step: that's the aperture, a real and recognizable feature, not
    an artifact to hide.

Plus HERO_AMMONITE_INNER (one tighter inner turn of the same spiral,
suggesting the coiled inner whorl) and HERO_AMMONITE_RIBS (growth ribs
radiating from it to the boundary) — detail that fades in once the
frame has actually become the ammonite shape.

Usage:
    python3 gen_hero_ammonite.py
"""

import json
import math
from pathlib import Path

OUT = Path(__file__).parent.parent / "assets" / "js" / "hero-portrait-data.js"

N = 120
CX, CY = 50.0, 50.0
TARGET_MAX_RADIUS = 44.0  # stay safely inside the 0-100 viewBox
GROWTH_RATIO = 1.8        # how much larger the shell is at the aperture vs. the start
SEAM = 0.4                # radians blended across the aperture seam


def blob_radius(theta):
    r = 38.0
    r += 3.0 * math.sin(3 * theta + 0.6)
    r += 1.7 * math.sin(5 * theta + 2.1)
    r += 1.0 * math.sin(2 * theta + 4.0)
    return r


def blob_radius_b(theta):
    """A second organic variant, same style, different phases/weights --
    continuously cross-fading between this and blob_radius() at rest is
    what makes the frame read as alive rather than a static wavy outline."""
    r = 38.0
    r += 2.6 * math.sin(3 * theta + 2.4)
    r += 2.1 * math.sin(4 * theta + 0.3)
    r += 1.3 * math.sin(6 * theta + 3.1)
    return r


def make_spiral_radius(a0, b):
    def spiral_radius(theta):
        return a0 * math.exp(b * theta)
    return spiral_radius


def ammonite_radius(theta, spiral_radius):
    t = theta % (2 * math.pi)
    base = spiral_radius(t)
    if t < SEAM:
        end_val = spiral_radius(2 * math.pi)
        f = t / SEAM
        f = f * f * (3 - 2 * f)  # smoothstep
        return end_val * (1 - f) + base * f
    return base


def pt(r, theta):
    return (round(CX + r * math.cos(theta), 2), round(CY + r * math.sin(theta), 2))


def main():
    thetas = [2 * math.pi * i / N for i in range(N)]

    b = math.log(GROWTH_RATIO) / (2 * math.pi)
    spiral_radius = make_spiral_radius(1.0, b)
    raw_max = max(ammonite_radius(t, spiral_radius) for t in thetas)
    a0 = TARGET_MAX_RADIUS / raw_max
    spiral_radius = make_spiral_radius(a0, b)

    mean_ammo = sum(ammonite_radius(t, spiral_radius) for t in thetas) / N
    mean_blob = sum(blob_radius(t) for t in thetas) / N
    blob_scale = mean_ammo / mean_blob

    blob_pts = [pt(blob_radius(t) * blob_scale, t) for t in thetas]
    blob_pts_b = [pt(blob_radius_b(t) * blob_scale, t) for t in thetas]
    ammo_pts = [pt(ammonite_radius(t, spiral_radius), t) for t in thetas]

    # inner whorl: one tighter turn of the same curve, offset inward
    inner_pts = []
    t = 0.0
    while t < 2 * math.pi * 0.96:
        inner_pts.append(pt(ammonite_radius(t, spiral_radius) * 0.55, t))
        t += 0.06
    inner_path = "M{},{} ".format(*inner_pts[0]) + " ".join(
        "L{},{}".format(*p) for p in inner_pts[1:]
    )

    # growth ribs: dense radiating strokes from near the center out to the
    # boundary, matching the fine engraved-fossil reference the user linked
    # (many closely-spaced radial ribs across the whole coil, not a sparse
    # few) — a real ammonite surface feature, not decoration.
    ribs = []
    t = 0.14
    while t < 2 * math.pi - 0.08:
        r_out = ammonite_radius(t, spiral_radius) * 0.96
        r_in = ammonite_radius(t, spiral_radius) * 0.16
        p_out = pt(r_out, t)
        p_in = pt(r_in, t)
        dx, dy = -math.sin(t), math.cos(t)
        mid = (round((p_out[0] + p_in[0]) / 2 - dx * 1.1, 2), round((p_out[1] + p_in[1]) / 2 - dy * 1.1, 2))
        ribs.append("M{},{} Q{},{} {},{}".format(p_in[0], p_in[1], mid[0], mid[1], p_out[0], p_out[1]))
        t += 0.105

    lines = [
        "/* Generated by scripts/gen_hero_ammonite.py — do not hand-edit. */",
        "var HERO_MORPH_BLOB = " + json.dumps(blob_pts) + ";",
        "var HERO_MORPH_BLOB_B = " + json.dumps(blob_pts_b) + ";",
        "var HERO_MORPH_AMMONITE = " + json.dumps(ammo_pts) + ";",
        "var HERO_AMMONITE_INNER = " + json.dumps(inner_path) + ";",
        "var HERO_AMMONITE_RIBS = " + json.dumps(ribs) + ";",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
